# Generated by Django 3.2.12 on 2022-03-09 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websiteApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Riddles',
            new_name='Riddle',
        ),
    ]
