# Generated by Django 3.2.12 on 2022-03-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteApp', '0002_rename_riddles_riddle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('points', models.IntegerField()),
            ],
        ),
    ]
